import crypto from "crypto";

/**
 * Generate a short hash from token content for versioning
 */
export function generateTokenHash(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex").slice(0, 7);
}

/**
 * Get current timestamp for generation metadata
 */
export function getTimestamp(): string {
  return new Date().toISOString();
}

/**
 * Generate file header with version info
 */
export function generateFileHeader(hash: string, type: "js" | "ts" | "css"): string {
  const comment = type === "css" ? "/*" : "//";
  const close = type === "css" ? " */" : "";
  
  return `${comment} Generated by Brakit Design Tokens${close}
${comment} Hash: ${hash}${close}
${comment} Timestamp: ${getTimestamp()}${close}
${comment} DO NOT EDIT - This file is auto-generated from .brakit/brakit.tokens.json${close}

`;
}
